/**
 * Generate typed API client from Effect HttpApi
 *
 * This script:
 * 1. Exports OpenAPI spec from the Effect HttpApi definition
 * 2. Runs openapi-typescript to generate TypeScript types
 *
 * The generated types are used with openapi-fetch for type-safe API calls.
 *
 * Usage: pnpm generate:api-client
 */
import { OpenApi } from "@effect/platform"
import openapiTS, { astToString } from "openapi-typescript"
import { AppApi } from "@accountability/api/Definitions/AppApi"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const spec = OpenApi.fromApi(AppApi)

console.log("Generating API client from Effect HttpApi...")
console.log(`  - OpenAPI: ${spec.openapi}`)
console.log(`  - Title: ${spec.info.title}`)
console.log(`  - Endpoints: ${Object.keys(spec.paths).length}`)
console.log(`  - Schemas: ${Object.keys(spec.components?.schemas ?? {}).length}`)

// Generate TypeScript types from OpenAPI spec
// @ts-expect-error - openapi-typescript expects OpenAPI spec, our type is compatible
const ast = await openapiTS(spec)
const contents = astToString(ast)

// Write to output files
const outputDir = path.join(__dirname, "../src/api")
const schemaFile = path.join(outputDir, "schema.ts")
const clientFile = path.join(outputDir, "client.ts")

fs.mkdirSync(outputDir, { recursive: true })
fs.writeFileSync(schemaFile, contents)

// Generate client wrapper
const clientCode = `/**
 * Generated API client
 *
 * DO NOT EDIT - This file is auto-generated by generate:api
 */
import createClient from "openapi-fetch"
import type { paths } from "./schema.ts"

export const api = createClient<paths>({
  baseUrl: typeof window !== "undefined" ? window.location.origin : "http://localhost:3000",
  credentials: "include"
})

export type { paths }
export type ApiClient = typeof api
`

fs.writeFileSync(clientFile, clientCode)

console.log(`\n✓ API types generated to ${schemaFile}`)
console.log(`✓ API client generated to ${clientFile}`)
