/**
 * Generated API client
 *
 * DO NOT EDIT - This file is auto-generated by generate:api
 */
import createClient from "openapi-fetch"
import type { paths } from "./schema.ts"

export const api = createClient<paths>({
  baseUrl: typeof window !== "undefined" ? window.location.origin : "http://localhost:3000",
  credentials: "include"
})

export type { paths }
export type ApiClient = typeof api
