/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlatformAdminsRouteImport } from './routes/platform-admins'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as OrganizationsNewRouteImport } from './routes/organizations/new'
import { Route as InvitationsTokenRouteImport } from './routes/invitations/$token'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as OrganizationsOrganizationIdRouteRouteImport } from './routes/organizations/$organizationId/route'
import { Route as OrganizationsOrganizationIdIndexRouteImport } from './routes/organizations/$organizationId/index'
import { Route as OrganizationsOrganizationIdSettingsRouteImport } from './routes/organizations/$organizationId/settings'
import { Route as OrganizationsOrganizationIdDashboardRouteImport } from './routes/organizations/$organizationId/dashboard'
import { Route as OrganizationsOrganizationIdSettingsIndexRouteImport } from './routes/organizations/$organizationId/settings/index'
import { Route as OrganizationsOrganizationIdReportsIndexRouteImport } from './routes/organizations/$organizationId/reports/index'
import { Route as OrganizationsOrganizationIdIntercompanyIndexRouteImport } from './routes/organizations/$organizationId/intercompany/index'
import { Route as OrganizationsOrganizationIdExchangeRatesIndexRouteImport } from './routes/organizations/$organizationId/exchange-rates/index'
import { Route as OrganizationsOrganizationIdConsolidationIndexRouteImport } from './routes/organizations/$organizationId/consolidation/index'
import { Route as OrganizationsOrganizationIdCompaniesIndexRouteImport } from './routes/organizations/$organizationId/companies/index'
import { Route as OrganizationsOrganizationIdAuditLogIndexRouteImport } from './routes/organizations/$organizationId/audit-log/index'
import { Route as OrganizationsOrganizationIdSettingsPoliciesRouteImport } from './routes/organizations/$organizationId/settings/policies'
import { Route as OrganizationsOrganizationIdSettingsMembersRouteImport } from './routes/organizations/$organizationId/settings/members'
import { Route as OrganizationsOrganizationIdSettingsAuthorizationAuditRouteImport } from './routes/organizations/$organizationId/settings/authorization-audit'
import { Route as OrganizationsOrganizationIdIntercompanyNewRouteImport } from './routes/organizations/$organizationId/intercompany/new'
import { Route as OrganizationsOrganizationIdExchangeRatesNewRouteImport } from './routes/organizations/$organizationId/exchange-rates/new'
import { Route as OrganizationsOrganizationIdConsolidationNewRouteImport } from './routes/organizations/$organizationId/consolidation/new'
import { Route as OrganizationsOrganizationIdCompaniesNewRouteImport } from './routes/organizations/$organizationId/companies/new'
import { Route as OrganizationsOrganizationIdIntercompanyTransactionIdIndexRouteImport } from './routes/organizations/$organizationId/intercompany/$transactionId/index'
import { Route as OrganizationsOrganizationIdConsolidationGroupIdIndexRouteImport } from './routes/organizations/$organizationId/consolidation/$groupId/index'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdIndexRouteImport } from './routes/organizations/$organizationId/companies/$companyId/index'
import { Route as OrganizationsOrganizationIdIntercompanyTransactionIdEditRouteImport } from './routes/organizations/$organizationId/intercompany/$transactionId/edit'
import { Route as OrganizationsOrganizationIdConsolidationGroupIdEditRouteImport } from './routes/organizations/$organizationId/consolidation/$groupId/edit'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdReportsIndexRouteImport } from './routes/organizations/$organizationId/companies/$companyId/reports/index'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRouteImport } from './routes/organizations/$organizationId/companies/$companyId/journal-entries/index'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdFiscalPeriodsIndexRouteImport } from './routes/organizations/$organizationId/companies/$companyId/fiscal-periods/index'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRouteImport } from './routes/organizations/$organizationId/companies/$companyId/accounts/index'
import { Route as OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteImport } from './routes/organizations/$organizationId/consolidation/$groupId/runs/$runId'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdReportsTrialBalanceRouteImport } from './routes/organizations/$organizationId/companies/$companyId/reports/trial-balance'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdReportsIncomeStatementRouteImport } from './routes/organizations/$organizationId/companies/$companyId/reports/income-statement'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdReportsEquityStatementRouteImport } from './routes/organizations/$organizationId/companies/$companyId/reports/equity-statement'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdReportsCashFlowRouteImport } from './routes/organizations/$organizationId/companies/$companyId/reports/cash-flow'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdReportsBalanceSheetRouteImport } from './routes/organizations/$organizationId/companies/$companyId/reports/balance-sheet'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRouteImport } from './routes/organizations/$organizationId/companies/$companyId/journal-entries/new'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRouteImport } from './routes/organizations/$organizationId/companies/$companyId/accounts/new'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdIndexRouteImport } from './routes/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/index'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdEditRouteImport } from './routes/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/edit'
import { Route as OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIndexRouteImport } from './routes/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/index'
import { Route as OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIncomeStatementRouteImport } from './routes/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/income-statement'
import { Route as OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsEquityStatementRouteImport } from './routes/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/equity-statement'
import { Route as OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsCashFlowRouteImport } from './routes/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/cash-flow'
import { Route as OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsBalanceSheetRouteImport } from './routes/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/balance-sheet'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminsRoute = PlatformAdminsRouteImport.update({
  id: '/platform-admins',
  path: '/platform-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenRoute = InvitationsTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => InvitationsRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationIdRouteRoute =
  OrganizationsOrganizationIdRouteRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdIndexRoute =
  OrganizationsOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdSettingsRoute =
  OrganizationsOrganizationIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdDashboardRoute =
  OrganizationsOrganizationIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdSettingsIndexRoute =
  OrganizationsOrganizationIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationsOrganizationIdSettingsRoute,
  } as any)
const OrganizationsOrganizationIdReportsIndexRoute =
  OrganizationsOrganizationIdReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdIntercompanyIndexRoute =
  OrganizationsOrganizationIdIntercompanyIndexRouteImport.update({
    id: '/intercompany/',
    path: '/intercompany/',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdExchangeRatesIndexRoute =
  OrganizationsOrganizationIdExchangeRatesIndexRouteImport.update({
    id: '/exchange-rates/',
    path: '/exchange-rates/',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdConsolidationIndexRoute =
  OrganizationsOrganizationIdConsolidationIndexRouteImport.update({
    id: '/consolidation/',
    path: '/consolidation/',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdCompaniesIndexRoute =
  OrganizationsOrganizationIdCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdAuditLogIndexRoute =
  OrganizationsOrganizationIdAuditLogIndexRouteImport.update({
    id: '/audit-log/',
    path: '/audit-log/',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdSettingsPoliciesRoute =
  OrganizationsOrganizationIdSettingsPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => OrganizationsOrganizationIdSettingsRoute,
  } as any)
const OrganizationsOrganizationIdSettingsMembersRoute =
  OrganizationsOrganizationIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => OrganizationsOrganizationIdSettingsRoute,
  } as any)
const OrganizationsOrganizationIdSettingsAuthorizationAuditRoute =
  OrganizationsOrganizationIdSettingsAuthorizationAuditRouteImport.update({
    id: '/authorization-audit',
    path: '/authorization-audit',
    getParentRoute: () => OrganizationsOrganizationIdSettingsRoute,
  } as any)
const OrganizationsOrganizationIdIntercompanyNewRoute =
  OrganizationsOrganizationIdIntercompanyNewRouteImport.update({
    id: '/intercompany/new',
    path: '/intercompany/new',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdExchangeRatesNewRoute =
  OrganizationsOrganizationIdExchangeRatesNewRouteImport.update({
    id: '/exchange-rates/new',
    path: '/exchange-rates/new',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdConsolidationNewRoute =
  OrganizationsOrganizationIdConsolidationNewRouteImport.update({
    id: '/consolidation/new',
    path: '/consolidation/new',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdCompaniesNewRoute =
  OrganizationsOrganizationIdCompaniesNewRouteImport.update({
    id: '/companies/new',
    path: '/companies/new',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdIntercompanyTransactionIdIndexRoute =
  OrganizationsOrganizationIdIntercompanyTransactionIdIndexRouteImport.update({
    id: '/intercompany/$transactionId/',
    path: '/intercompany/$transactionId/',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdConsolidationGroupIdIndexRoute =
  OrganizationsOrganizationIdConsolidationGroupIdIndexRouteImport.update({
    id: '/consolidation/$groupId/',
    path: '/consolidation/$groupId/',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdIndexRouteImport.update({
    id: '/companies/$companyId/',
    path: '/companies/$companyId/',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdIntercompanyTransactionIdEditRoute =
  OrganizationsOrganizationIdIntercompanyTransactionIdEditRouteImport.update({
    id: '/intercompany/$transactionId/edit',
    path: '/intercompany/$transactionId/edit',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdConsolidationGroupIdEditRoute =
  OrganizationsOrganizationIdConsolidationGroupIdEditRouteImport.update({
    id: '/consolidation/$groupId/edit',
    path: '/consolidation/$groupId/edit',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdCompaniesCompanyIdReportsIndexRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdReportsIndexRouteImport.update({
    id: '/companies/$companyId/reports/',
    path: '/companies/$companyId/reports/',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRouteImport.update(
    {
      id: '/companies/$companyId/journal-entries/',
      path: '/companies/$companyId/journal-entries/',
      getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
    } as any,
  )
const OrganizationsOrganizationIdCompaniesCompanyIdFiscalPeriodsIndexRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdFiscalPeriodsIndexRouteImport.update(
    {
      id: '/companies/$companyId/fiscal-periods/',
      path: '/companies/$companyId/fiscal-periods/',
      getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
    } as any,
  )
const OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRouteImport.update({
    id: '/companies/$companyId/accounts/',
    path: '/companies/$companyId/accounts/',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute =
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteImport.update({
    id: '/consolidation/$groupId/runs/$runId',
    path: '/consolidation/$groupId/runs/$runId',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdCompaniesCompanyIdReportsTrialBalanceRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdReportsTrialBalanceRouteImport.update(
    {
      id: '/companies/$companyId/reports/trial-balance',
      path: '/companies/$companyId/reports/trial-balance',
      getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
    } as any,
  )
const OrganizationsOrganizationIdCompaniesCompanyIdReportsIncomeStatementRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdReportsIncomeStatementRouteImport.update(
    {
      id: '/companies/$companyId/reports/income-statement',
      path: '/companies/$companyId/reports/income-statement',
      getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
    } as any,
  )
const OrganizationsOrganizationIdCompaniesCompanyIdReportsEquityStatementRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdReportsEquityStatementRouteImport.update(
    {
      id: '/companies/$companyId/reports/equity-statement',
      path: '/companies/$companyId/reports/equity-statement',
      getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
    } as any,
  )
const OrganizationsOrganizationIdCompaniesCompanyIdReportsCashFlowRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdReportsCashFlowRouteImport.update(
    {
      id: '/companies/$companyId/reports/cash-flow',
      path: '/companies/$companyId/reports/cash-flow',
      getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
    } as any,
  )
const OrganizationsOrganizationIdCompaniesCompanyIdReportsBalanceSheetRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdReportsBalanceSheetRouteImport.update(
    {
      id: '/companies/$companyId/reports/balance-sheet',
      path: '/companies/$companyId/reports/balance-sheet',
      getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
    } as any,
  )
const OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRouteImport.update(
    {
      id: '/companies/$companyId/journal-entries/new',
      path: '/companies/$companyId/journal-entries/new',
      getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
    } as any,
  )
const OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRouteImport.update({
    id: '/companies/$companyId/accounts/new',
    path: '/companies/$companyId/accounts/new',
    getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
  } as any)
const OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdIndexRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdIndexRouteImport.update(
    {
      id: '/companies/$companyId/journal-entries/$entryId/',
      path: '/companies/$companyId/journal-entries/$entryId/',
      getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
    } as any,
  )
const OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdEditRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdEditRouteImport.update(
    {
      id: '/companies/$companyId/journal-entries/$entryId/edit',
      path: '/companies/$companyId/journal-entries/$entryId/edit',
      getParentRoute: () => OrganizationsOrganizationIdRouteRoute,
    } as any,
  )
const OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIndexRoute =
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIndexRouteImport.update(
    {
      id: '/reports/',
      path: '/reports/',
      getParentRoute: () =>
        OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute,
    } as any,
  )
const OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIncomeStatementRoute =
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIncomeStatementRouteImport.update(
    {
      id: '/reports/income-statement',
      path: '/reports/income-statement',
      getParentRoute: () =>
        OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute,
    } as any,
  )
const OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsEquityStatementRoute =
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsEquityStatementRouteImport.update(
    {
      id: '/reports/equity-statement',
      path: '/reports/equity-statement',
      getParentRoute: () =>
        OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute,
    } as any,
  )
const OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsCashFlowRoute =
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsCashFlowRouteImport.update(
    {
      id: '/reports/cash-flow',
      path: '/reports/cash-flow',
      getParentRoute: () =>
        OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute,
    } as any,
  )
const OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsBalanceSheetRoute =
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsBalanceSheetRouteImport.update(
    {
      id: '/reports/balance-sheet',
      path: '/reports/balance-sheet',
      getParentRoute: () =>
        OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRouteWithChildren
  '/login': typeof LoginRoute
  '/platform-admins': typeof PlatformAdminsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/organizations/$organizationId/dashboard': typeof OrganizationsOrganizationIdDashboardRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRouteWithChildren
  '/organizations/$organizationId/': typeof OrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/companies/new': typeof OrganizationsOrganizationIdCompaniesNewRoute
  '/organizations/$organizationId/consolidation/new': typeof OrganizationsOrganizationIdConsolidationNewRoute
  '/organizations/$organizationId/exchange-rates/new': typeof OrganizationsOrganizationIdExchangeRatesNewRoute
  '/organizations/$organizationId/intercompany/new': typeof OrganizationsOrganizationIdIntercompanyNewRoute
  '/organizations/$organizationId/settings/authorization-audit': typeof OrganizationsOrganizationIdSettingsAuthorizationAuditRoute
  '/organizations/$organizationId/settings/members': typeof OrganizationsOrganizationIdSettingsMembersRoute
  '/organizations/$organizationId/settings/policies': typeof OrganizationsOrganizationIdSettingsPoliciesRoute
  '/organizations/$organizationId/audit-log': typeof OrganizationsOrganizationIdAuditLogIndexRoute
  '/organizations/$organizationId/companies': typeof OrganizationsOrganizationIdCompaniesIndexRoute
  '/organizations/$organizationId/consolidation': typeof OrganizationsOrganizationIdConsolidationIndexRoute
  '/organizations/$organizationId/exchange-rates': typeof OrganizationsOrganizationIdExchangeRatesIndexRoute
  '/organizations/$organizationId/intercompany': typeof OrganizationsOrganizationIdIntercompanyIndexRoute
  '/organizations/$organizationId/reports': typeof OrganizationsOrganizationIdReportsIndexRoute
  '/organizations/$organizationId/settings/': typeof OrganizationsOrganizationIdSettingsIndexRoute
  '/organizations/$organizationId/consolidation/$groupId/edit': typeof OrganizationsOrganizationIdConsolidationGroupIdEditRoute
  '/organizations/$organizationId/intercompany/$transactionId/edit': typeof OrganizationsOrganizationIdIntercompanyTransactionIdEditRoute
  '/organizations/$organizationId/companies/$companyId': typeof OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute
  '/organizations/$organizationId/consolidation/$groupId': typeof OrganizationsOrganizationIdConsolidationGroupIdIndexRoute
  '/organizations/$organizationId/intercompany/$transactionId': typeof OrganizationsOrganizationIdIntercompanyTransactionIdIndexRoute
  '/organizations/$organizationId/companies/$companyId/accounts/new': typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/new': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute
  '/organizations/$organizationId/companies/$companyId/reports/balance-sheet': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsBalanceSheetRoute
  '/organizations/$organizationId/companies/$companyId/reports/cash-flow': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsCashFlowRoute
  '/organizations/$organizationId/companies/$companyId/reports/equity-statement': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsEquityStatementRoute
  '/organizations/$organizationId/companies/$companyId/reports/income-statement': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsIncomeStatementRoute
  '/organizations/$organizationId/companies/$companyId/reports/trial-balance': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsTrialBalanceRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteWithChildren
  '/organizations/$organizationId/companies/$companyId/accounts': typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute
  '/organizations/$organizationId/companies/$companyId/fiscal-periods': typeof OrganizationsOrganizationIdCompaniesCompanyIdFiscalPeriodsIndexRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute
  '/organizations/$organizationId/companies/$companyId/reports': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsIndexRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/edit': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdEditRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdIndexRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/balance-sheet': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsBalanceSheetRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/cash-flow': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsCashFlowRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/equity-statement': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsEquityStatementRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/income-statement': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIncomeStatementRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRouteWithChildren
  '/login': typeof LoginRoute
  '/platform-admins': typeof PlatformAdminsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/organizations/$organizationId/dashboard': typeof OrganizationsOrganizationIdDashboardRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/companies/new': typeof OrganizationsOrganizationIdCompaniesNewRoute
  '/organizations/$organizationId/consolidation/new': typeof OrganizationsOrganizationIdConsolidationNewRoute
  '/organizations/$organizationId/exchange-rates/new': typeof OrganizationsOrganizationIdExchangeRatesNewRoute
  '/organizations/$organizationId/intercompany/new': typeof OrganizationsOrganizationIdIntercompanyNewRoute
  '/organizations/$organizationId/settings/authorization-audit': typeof OrganizationsOrganizationIdSettingsAuthorizationAuditRoute
  '/organizations/$organizationId/settings/members': typeof OrganizationsOrganizationIdSettingsMembersRoute
  '/organizations/$organizationId/settings/policies': typeof OrganizationsOrganizationIdSettingsPoliciesRoute
  '/organizations/$organizationId/audit-log': typeof OrganizationsOrganizationIdAuditLogIndexRoute
  '/organizations/$organizationId/companies': typeof OrganizationsOrganizationIdCompaniesIndexRoute
  '/organizations/$organizationId/consolidation': typeof OrganizationsOrganizationIdConsolidationIndexRoute
  '/organizations/$organizationId/exchange-rates': typeof OrganizationsOrganizationIdExchangeRatesIndexRoute
  '/organizations/$organizationId/intercompany': typeof OrganizationsOrganizationIdIntercompanyIndexRoute
  '/organizations/$organizationId/reports': typeof OrganizationsOrganizationIdReportsIndexRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsIndexRoute
  '/organizations/$organizationId/consolidation/$groupId/edit': typeof OrganizationsOrganizationIdConsolidationGroupIdEditRoute
  '/organizations/$organizationId/intercompany/$transactionId/edit': typeof OrganizationsOrganizationIdIntercompanyTransactionIdEditRoute
  '/organizations/$organizationId/companies/$companyId': typeof OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute
  '/organizations/$organizationId/consolidation/$groupId': typeof OrganizationsOrganizationIdConsolidationGroupIdIndexRoute
  '/organizations/$organizationId/intercompany/$transactionId': typeof OrganizationsOrganizationIdIntercompanyTransactionIdIndexRoute
  '/organizations/$organizationId/companies/$companyId/accounts/new': typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/new': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute
  '/organizations/$organizationId/companies/$companyId/reports/balance-sheet': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsBalanceSheetRoute
  '/organizations/$organizationId/companies/$companyId/reports/cash-flow': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsCashFlowRoute
  '/organizations/$organizationId/companies/$companyId/reports/equity-statement': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsEquityStatementRoute
  '/organizations/$organizationId/companies/$companyId/reports/income-statement': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsIncomeStatementRoute
  '/organizations/$organizationId/companies/$companyId/reports/trial-balance': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsTrialBalanceRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteWithChildren
  '/organizations/$organizationId/companies/$companyId/accounts': typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute
  '/organizations/$organizationId/companies/$companyId/fiscal-periods': typeof OrganizationsOrganizationIdCompaniesCompanyIdFiscalPeriodsIndexRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute
  '/organizations/$organizationId/companies/$companyId/reports': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsIndexRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/edit': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdEditRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdIndexRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/balance-sheet': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsBalanceSheetRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/cash-flow': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsCashFlowRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/equity-statement': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsEquityStatementRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/income-statement': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIncomeStatementRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRouteWithChildren
  '/login': typeof LoginRoute
  '/platform-admins': typeof PlatformAdminsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/organizations/$organizationId/dashboard': typeof OrganizationsOrganizationIdDashboardRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRouteWithChildren
  '/organizations/$organizationId/': typeof OrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/companies/new': typeof OrganizationsOrganizationIdCompaniesNewRoute
  '/organizations/$organizationId/consolidation/new': typeof OrganizationsOrganizationIdConsolidationNewRoute
  '/organizations/$organizationId/exchange-rates/new': typeof OrganizationsOrganizationIdExchangeRatesNewRoute
  '/organizations/$organizationId/intercompany/new': typeof OrganizationsOrganizationIdIntercompanyNewRoute
  '/organizations/$organizationId/settings/authorization-audit': typeof OrganizationsOrganizationIdSettingsAuthorizationAuditRoute
  '/organizations/$organizationId/settings/members': typeof OrganizationsOrganizationIdSettingsMembersRoute
  '/organizations/$organizationId/settings/policies': typeof OrganizationsOrganizationIdSettingsPoliciesRoute
  '/organizations/$organizationId/audit-log/': typeof OrganizationsOrganizationIdAuditLogIndexRoute
  '/organizations/$organizationId/companies/': typeof OrganizationsOrganizationIdCompaniesIndexRoute
  '/organizations/$organizationId/consolidation/': typeof OrganizationsOrganizationIdConsolidationIndexRoute
  '/organizations/$organizationId/exchange-rates/': typeof OrganizationsOrganizationIdExchangeRatesIndexRoute
  '/organizations/$organizationId/intercompany/': typeof OrganizationsOrganizationIdIntercompanyIndexRoute
  '/organizations/$organizationId/reports/': typeof OrganizationsOrganizationIdReportsIndexRoute
  '/organizations/$organizationId/settings/': typeof OrganizationsOrganizationIdSettingsIndexRoute
  '/organizations/$organizationId/consolidation/$groupId/edit': typeof OrganizationsOrganizationIdConsolidationGroupIdEditRoute
  '/organizations/$organizationId/intercompany/$transactionId/edit': typeof OrganizationsOrganizationIdIntercompanyTransactionIdEditRoute
  '/organizations/$organizationId/companies/$companyId/': typeof OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute
  '/organizations/$organizationId/consolidation/$groupId/': typeof OrganizationsOrganizationIdConsolidationGroupIdIndexRoute
  '/organizations/$organizationId/intercompany/$transactionId/': typeof OrganizationsOrganizationIdIntercompanyTransactionIdIndexRoute
  '/organizations/$organizationId/companies/$companyId/accounts/new': typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/new': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute
  '/organizations/$organizationId/companies/$companyId/reports/balance-sheet': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsBalanceSheetRoute
  '/organizations/$organizationId/companies/$companyId/reports/cash-flow': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsCashFlowRoute
  '/organizations/$organizationId/companies/$companyId/reports/equity-statement': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsEquityStatementRoute
  '/organizations/$organizationId/companies/$companyId/reports/income-statement': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsIncomeStatementRoute
  '/organizations/$organizationId/companies/$companyId/reports/trial-balance': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsTrialBalanceRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteWithChildren
  '/organizations/$organizationId/companies/$companyId/accounts/': typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute
  '/organizations/$organizationId/companies/$companyId/fiscal-periods/': typeof OrganizationsOrganizationIdCompaniesCompanyIdFiscalPeriodsIndexRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute
  '/organizations/$organizationId/companies/$companyId/reports/': typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsIndexRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/edit': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdEditRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdIndexRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/balance-sheet': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsBalanceSheetRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/cash-flow': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsCashFlowRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/equity-statement': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsEquityStatementRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/income-statement': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIncomeStatementRoute
  '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/': typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invitations'
    | '/login'
    | '/platform-admins'
    | '/profile'
    | '/register'
    | '/organizations/$organizationId'
    | '/api/$'
    | '/invitations/$token'
    | '/organizations/new'
    | '/organizations'
    | '/organizations/$organizationId/dashboard'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId/'
    | '/organizations/$organizationId/companies/new'
    | '/organizations/$organizationId/consolidation/new'
    | '/organizations/$organizationId/exchange-rates/new'
    | '/organizations/$organizationId/intercompany/new'
    | '/organizations/$organizationId/settings/authorization-audit'
    | '/organizations/$organizationId/settings/members'
    | '/organizations/$organizationId/settings/policies'
    | '/organizations/$organizationId/audit-log'
    | '/organizations/$organizationId/companies'
    | '/organizations/$organizationId/consolidation'
    | '/organizations/$organizationId/exchange-rates'
    | '/organizations/$organizationId/intercompany'
    | '/organizations/$organizationId/reports'
    | '/organizations/$organizationId/settings/'
    | '/organizations/$organizationId/consolidation/$groupId/edit'
    | '/organizations/$organizationId/intercompany/$transactionId/edit'
    | '/organizations/$organizationId/companies/$companyId'
    | '/organizations/$organizationId/consolidation/$groupId'
    | '/organizations/$organizationId/intercompany/$transactionId'
    | '/organizations/$organizationId/companies/$companyId/accounts/new'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/new'
    | '/organizations/$organizationId/companies/$companyId/reports/balance-sheet'
    | '/organizations/$organizationId/companies/$companyId/reports/cash-flow'
    | '/organizations/$organizationId/companies/$companyId/reports/equity-statement'
    | '/organizations/$organizationId/companies/$companyId/reports/income-statement'
    | '/organizations/$organizationId/companies/$companyId/reports/trial-balance'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId'
    | '/organizations/$organizationId/companies/$companyId/accounts'
    | '/organizations/$organizationId/companies/$companyId/fiscal-periods'
    | '/organizations/$organizationId/companies/$companyId/journal-entries'
    | '/organizations/$organizationId/companies/$companyId/reports'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/edit'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/balance-sheet'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/cash-flow'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/equity-statement'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/income-statement'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invitations'
    | '/login'
    | '/platform-admins'
    | '/profile'
    | '/register'
    | '/api/$'
    | '/invitations/$token'
    | '/organizations/new'
    | '/organizations'
    | '/organizations/$organizationId/dashboard'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/companies/new'
    | '/organizations/$organizationId/consolidation/new'
    | '/organizations/$organizationId/exchange-rates/new'
    | '/organizations/$organizationId/intercompany/new'
    | '/organizations/$organizationId/settings/authorization-audit'
    | '/organizations/$organizationId/settings/members'
    | '/organizations/$organizationId/settings/policies'
    | '/organizations/$organizationId/audit-log'
    | '/organizations/$organizationId/companies'
    | '/organizations/$organizationId/consolidation'
    | '/organizations/$organizationId/exchange-rates'
    | '/organizations/$organizationId/intercompany'
    | '/organizations/$organizationId/reports'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId/consolidation/$groupId/edit'
    | '/organizations/$organizationId/intercompany/$transactionId/edit'
    | '/organizations/$organizationId/companies/$companyId'
    | '/organizations/$organizationId/consolidation/$groupId'
    | '/organizations/$organizationId/intercompany/$transactionId'
    | '/organizations/$organizationId/companies/$companyId/accounts/new'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/new'
    | '/organizations/$organizationId/companies/$companyId/reports/balance-sheet'
    | '/organizations/$organizationId/companies/$companyId/reports/cash-flow'
    | '/organizations/$organizationId/companies/$companyId/reports/equity-statement'
    | '/organizations/$organizationId/companies/$companyId/reports/income-statement'
    | '/organizations/$organizationId/companies/$companyId/reports/trial-balance'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId'
    | '/organizations/$organizationId/companies/$companyId/accounts'
    | '/organizations/$organizationId/companies/$companyId/fiscal-periods'
    | '/organizations/$organizationId/companies/$companyId/journal-entries'
    | '/organizations/$organizationId/companies/$companyId/reports'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/edit'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/balance-sheet'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/cash-flow'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/equity-statement'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/income-statement'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports'
  id:
    | '__root__'
    | '/'
    | '/invitations'
    | '/login'
    | '/platform-admins'
    | '/profile'
    | '/register'
    | '/organizations/$organizationId'
    | '/api/$'
    | '/invitations/$token'
    | '/organizations/new'
    | '/organizations/'
    | '/organizations/$organizationId/dashboard'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId/'
    | '/organizations/$organizationId/companies/new'
    | '/organizations/$organizationId/consolidation/new'
    | '/organizations/$organizationId/exchange-rates/new'
    | '/organizations/$organizationId/intercompany/new'
    | '/organizations/$organizationId/settings/authorization-audit'
    | '/organizations/$organizationId/settings/members'
    | '/organizations/$organizationId/settings/policies'
    | '/organizations/$organizationId/audit-log/'
    | '/organizations/$organizationId/companies/'
    | '/organizations/$organizationId/consolidation/'
    | '/organizations/$organizationId/exchange-rates/'
    | '/organizations/$organizationId/intercompany/'
    | '/organizations/$organizationId/reports/'
    | '/organizations/$organizationId/settings/'
    | '/organizations/$organizationId/consolidation/$groupId/edit'
    | '/organizations/$organizationId/intercompany/$transactionId/edit'
    | '/organizations/$organizationId/companies/$companyId/'
    | '/organizations/$organizationId/consolidation/$groupId/'
    | '/organizations/$organizationId/intercompany/$transactionId/'
    | '/organizations/$organizationId/companies/$companyId/accounts/new'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/new'
    | '/organizations/$organizationId/companies/$companyId/reports/balance-sheet'
    | '/organizations/$organizationId/companies/$companyId/reports/cash-flow'
    | '/organizations/$organizationId/companies/$companyId/reports/equity-statement'
    | '/organizations/$organizationId/companies/$companyId/reports/income-statement'
    | '/organizations/$organizationId/companies/$companyId/reports/trial-balance'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId'
    | '/organizations/$organizationId/companies/$companyId/accounts/'
    | '/organizations/$organizationId/companies/$companyId/fiscal-periods/'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/'
    | '/organizations/$organizationId/companies/$companyId/reports/'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/edit'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/balance-sheet'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/cash-flow'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/equity-statement'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/income-statement'
    | '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitationsRoute: typeof InvitationsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlatformAdminsRoute: typeof PlatformAdminsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  OrganizationsOrganizationIdRouteRoute: typeof OrganizationsOrganizationIdRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admins': {
      id: '/platform-admins'
      path: '/platform-admins'
      fullPath: '/platform-admins'
      preLoaderRoute: typeof PlatformAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token': {
      id: '/invitations/$token'
      path: '/$token'
      fullPath: '/invitations/$token'
      preLoaderRoute: typeof InvitationsTokenRouteImport
      parentRoute: typeof InvitationsRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId': {
      id: '/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/': {
      id: '/organizations/$organizationId/'
      path: '/'
      fullPath: '/organizations/$organizationId/'
      preLoaderRoute: typeof OrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/settings': {
      id: '/organizations/$organizationId/settings'
      path: '/settings'
      fullPath: '/organizations/$organizationId/settings'
      preLoaderRoute: typeof OrganizationsOrganizationIdSettingsRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/dashboard': {
      id: '/organizations/$organizationId/dashboard'
      path: '/dashboard'
      fullPath: '/organizations/$organizationId/dashboard'
      preLoaderRoute: typeof OrganizationsOrganizationIdDashboardRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/settings/': {
      id: '/organizations/$organizationId/settings/'
      path: '/'
      fullPath: '/organizations/$organizationId/settings/'
      preLoaderRoute: typeof OrganizationsOrganizationIdSettingsIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdSettingsRoute
    }
    '/organizations/$organizationId/reports/': {
      id: '/organizations/$organizationId/reports/'
      path: '/reports'
      fullPath: '/organizations/$organizationId/reports'
      preLoaderRoute: typeof OrganizationsOrganizationIdReportsIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/intercompany/': {
      id: '/organizations/$organizationId/intercompany/'
      path: '/intercompany'
      fullPath: '/organizations/$organizationId/intercompany'
      preLoaderRoute: typeof OrganizationsOrganizationIdIntercompanyIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/exchange-rates/': {
      id: '/organizations/$organizationId/exchange-rates/'
      path: '/exchange-rates'
      fullPath: '/organizations/$organizationId/exchange-rates'
      preLoaderRoute: typeof OrganizationsOrganizationIdExchangeRatesIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/consolidation/': {
      id: '/organizations/$organizationId/consolidation/'
      path: '/consolidation'
      fullPath: '/organizations/$organizationId/consolidation'
      preLoaderRoute: typeof OrganizationsOrganizationIdConsolidationIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/': {
      id: '/organizations/$organizationId/companies/'
      path: '/companies'
      fullPath: '/organizations/$organizationId/companies'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/audit-log/': {
      id: '/organizations/$organizationId/audit-log/'
      path: '/audit-log'
      fullPath: '/organizations/$organizationId/audit-log'
      preLoaderRoute: typeof OrganizationsOrganizationIdAuditLogIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/settings/policies': {
      id: '/organizations/$organizationId/settings/policies'
      path: '/policies'
      fullPath: '/organizations/$organizationId/settings/policies'
      preLoaderRoute: typeof OrganizationsOrganizationIdSettingsPoliciesRouteImport
      parentRoute: typeof OrganizationsOrganizationIdSettingsRoute
    }
    '/organizations/$organizationId/settings/members': {
      id: '/organizations/$organizationId/settings/members'
      path: '/members'
      fullPath: '/organizations/$organizationId/settings/members'
      preLoaderRoute: typeof OrganizationsOrganizationIdSettingsMembersRouteImport
      parentRoute: typeof OrganizationsOrganizationIdSettingsRoute
    }
    '/organizations/$organizationId/settings/authorization-audit': {
      id: '/organizations/$organizationId/settings/authorization-audit'
      path: '/authorization-audit'
      fullPath: '/organizations/$organizationId/settings/authorization-audit'
      preLoaderRoute: typeof OrganizationsOrganizationIdSettingsAuthorizationAuditRouteImport
      parentRoute: typeof OrganizationsOrganizationIdSettingsRoute
    }
    '/organizations/$organizationId/intercompany/new': {
      id: '/organizations/$organizationId/intercompany/new'
      path: '/intercompany/new'
      fullPath: '/organizations/$organizationId/intercompany/new'
      preLoaderRoute: typeof OrganizationsOrganizationIdIntercompanyNewRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/exchange-rates/new': {
      id: '/organizations/$organizationId/exchange-rates/new'
      path: '/exchange-rates/new'
      fullPath: '/organizations/$organizationId/exchange-rates/new'
      preLoaderRoute: typeof OrganizationsOrganizationIdExchangeRatesNewRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/consolidation/new': {
      id: '/organizations/$organizationId/consolidation/new'
      path: '/consolidation/new'
      fullPath: '/organizations/$organizationId/consolidation/new'
      preLoaderRoute: typeof OrganizationsOrganizationIdConsolidationNewRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/new': {
      id: '/organizations/$organizationId/companies/new'
      path: '/companies/new'
      fullPath: '/organizations/$organizationId/companies/new'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesNewRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/intercompany/$transactionId/': {
      id: '/organizations/$organizationId/intercompany/$transactionId/'
      path: '/intercompany/$transactionId'
      fullPath: '/organizations/$organizationId/intercompany/$transactionId'
      preLoaderRoute: typeof OrganizationsOrganizationIdIntercompanyTransactionIdIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/consolidation/$groupId/': {
      id: '/organizations/$organizationId/consolidation/$groupId/'
      path: '/consolidation/$groupId'
      fullPath: '/organizations/$organizationId/consolidation/$groupId'
      preLoaderRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/': {
      id: '/organizations/$organizationId/companies/$companyId/'
      path: '/companies/$companyId'
      fullPath: '/organizations/$organizationId/companies/$companyId'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/intercompany/$transactionId/edit': {
      id: '/organizations/$organizationId/intercompany/$transactionId/edit'
      path: '/intercompany/$transactionId/edit'
      fullPath: '/organizations/$organizationId/intercompany/$transactionId/edit'
      preLoaderRoute: typeof OrganizationsOrganizationIdIntercompanyTransactionIdEditRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/consolidation/$groupId/edit': {
      id: '/organizations/$organizationId/consolidation/$groupId/edit'
      path: '/consolidation/$groupId/edit'
      fullPath: '/organizations/$organizationId/consolidation/$groupId/edit'
      preLoaderRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdEditRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/reports/': {
      id: '/organizations/$organizationId/companies/$companyId/reports/'
      path: '/companies/$companyId/reports'
      fullPath: '/organizations/$organizationId/companies/$companyId/reports'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/journal-entries/': {
      id: '/organizations/$organizationId/companies/$companyId/journal-entries/'
      path: '/companies/$companyId/journal-entries'
      fullPath: '/organizations/$organizationId/companies/$companyId/journal-entries'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/fiscal-periods/': {
      id: '/organizations/$organizationId/companies/$companyId/fiscal-periods/'
      path: '/companies/$companyId/fiscal-periods'
      fullPath: '/organizations/$organizationId/companies/$companyId/fiscal-periods'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdFiscalPeriodsIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/accounts/': {
      id: '/organizations/$organizationId/companies/$companyId/accounts/'
      path: '/companies/$companyId/accounts'
      fullPath: '/organizations/$organizationId/companies/$companyId/accounts'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/consolidation/$groupId/runs/$runId': {
      id: '/organizations/$organizationId/consolidation/$groupId/runs/$runId'
      path: '/consolidation/$groupId/runs/$runId'
      fullPath: '/organizations/$organizationId/consolidation/$groupId/runs/$runId'
      preLoaderRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/reports/trial-balance': {
      id: '/organizations/$organizationId/companies/$companyId/reports/trial-balance'
      path: '/companies/$companyId/reports/trial-balance'
      fullPath: '/organizations/$organizationId/companies/$companyId/reports/trial-balance'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsTrialBalanceRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/reports/income-statement': {
      id: '/organizations/$organizationId/companies/$companyId/reports/income-statement'
      path: '/companies/$companyId/reports/income-statement'
      fullPath: '/organizations/$organizationId/companies/$companyId/reports/income-statement'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsIncomeStatementRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/reports/equity-statement': {
      id: '/organizations/$organizationId/companies/$companyId/reports/equity-statement'
      path: '/companies/$companyId/reports/equity-statement'
      fullPath: '/organizations/$organizationId/companies/$companyId/reports/equity-statement'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsEquityStatementRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/reports/cash-flow': {
      id: '/organizations/$organizationId/companies/$companyId/reports/cash-flow'
      path: '/companies/$companyId/reports/cash-flow'
      fullPath: '/organizations/$organizationId/companies/$companyId/reports/cash-flow'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsCashFlowRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/reports/balance-sheet': {
      id: '/organizations/$organizationId/companies/$companyId/reports/balance-sheet'
      path: '/companies/$companyId/reports/balance-sheet'
      fullPath: '/organizations/$organizationId/companies/$companyId/reports/balance-sheet'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsBalanceSheetRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/journal-entries/new': {
      id: '/organizations/$organizationId/companies/$companyId/journal-entries/new'
      path: '/companies/$companyId/journal-entries/new'
      fullPath: '/organizations/$organizationId/companies/$companyId/journal-entries/new'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/accounts/new': {
      id: '/organizations/$organizationId/companies/$companyId/accounts/new'
      path: '/companies/$companyId/accounts/new'
      fullPath: '/organizations/$organizationId/companies/$companyId/accounts/new'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/': {
      id: '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/'
      path: '/companies/$companyId/journal-entries/$entryId'
      fullPath: '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/edit': {
      id: '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/edit'
      path: '/companies/$companyId/journal-entries/$entryId/edit'
      fullPath: '/organizations/$organizationId/companies/$companyId/journal-entries/$entryId/edit'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdEditRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRouteRoute
    }
    '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/': {
      id: '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/'
      path: '/reports'
      fullPath: '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports'
      preLoaderRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIndexRouteImport
      parentRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute
    }
    '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/income-statement': {
      id: '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/income-statement'
      path: '/reports/income-statement'
      fullPath: '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/income-statement'
      preLoaderRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIncomeStatementRouteImport
      parentRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute
    }
    '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/equity-statement': {
      id: '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/equity-statement'
      path: '/reports/equity-statement'
      fullPath: '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/equity-statement'
      preLoaderRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsEquityStatementRouteImport
      parentRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute
    }
    '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/cash-flow': {
      id: '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/cash-flow'
      path: '/reports/cash-flow'
      fullPath: '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/cash-flow'
      preLoaderRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsCashFlowRouteImport
      parentRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute
    }
    '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/balance-sheet': {
      id: '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/organizations/$organizationId/consolidation/$groupId/runs/$runId/reports/balance-sheet'
      preLoaderRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsBalanceSheetRouteImport
      parentRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute
    }
  }
}

interface InvitationsRouteChildren {
  InvitationsTokenRoute: typeof InvitationsTokenRoute
}

const InvitationsRouteChildren: InvitationsRouteChildren = {
  InvitationsTokenRoute: InvitationsTokenRoute,
}

const InvitationsRouteWithChildren = InvitationsRoute._addFileChildren(
  InvitationsRouteChildren,
)

interface OrganizationsOrganizationIdSettingsRouteChildren {
  OrganizationsOrganizationIdSettingsAuthorizationAuditRoute: typeof OrganizationsOrganizationIdSettingsAuthorizationAuditRoute
  OrganizationsOrganizationIdSettingsMembersRoute: typeof OrganizationsOrganizationIdSettingsMembersRoute
  OrganizationsOrganizationIdSettingsPoliciesRoute: typeof OrganizationsOrganizationIdSettingsPoliciesRoute
  OrganizationsOrganizationIdSettingsIndexRoute: typeof OrganizationsOrganizationIdSettingsIndexRoute
}

const OrganizationsOrganizationIdSettingsRouteChildren: OrganizationsOrganizationIdSettingsRouteChildren =
  {
    OrganizationsOrganizationIdSettingsAuthorizationAuditRoute:
      OrganizationsOrganizationIdSettingsAuthorizationAuditRoute,
    OrganizationsOrganizationIdSettingsMembersRoute:
      OrganizationsOrganizationIdSettingsMembersRoute,
    OrganizationsOrganizationIdSettingsPoliciesRoute:
      OrganizationsOrganizationIdSettingsPoliciesRoute,
    OrganizationsOrganizationIdSettingsIndexRoute:
      OrganizationsOrganizationIdSettingsIndexRoute,
  }

const OrganizationsOrganizationIdSettingsRouteWithChildren =
  OrganizationsOrganizationIdSettingsRoute._addFileChildren(
    OrganizationsOrganizationIdSettingsRouteChildren,
  )

interface OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteChildren {
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsBalanceSheetRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsBalanceSheetRoute
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsCashFlowRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsCashFlowRoute
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsEquityStatementRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsEquityStatementRoute
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIncomeStatementRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIncomeStatementRoute
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIndexRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIndexRoute
}

const OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteChildren: OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteChildren =
  {
    OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsBalanceSheetRoute:
      OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsBalanceSheetRoute,
    OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsCashFlowRoute:
      OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsCashFlowRoute,
    OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsEquityStatementRoute:
      OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsEquityStatementRoute,
    OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIncomeStatementRoute:
      OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIncomeStatementRoute,
    OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIndexRoute:
      OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdReportsIndexRoute,
  }

const OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteWithChildren =
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute._addFileChildren(
    OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteChildren,
  )

interface OrganizationsOrganizationIdRouteRouteChildren {
  OrganizationsOrganizationIdDashboardRoute: typeof OrganizationsOrganizationIdDashboardRoute
  OrganizationsOrganizationIdSettingsRoute: typeof OrganizationsOrganizationIdSettingsRouteWithChildren
  OrganizationsOrganizationIdIndexRoute: typeof OrganizationsOrganizationIdIndexRoute
  OrganizationsOrganizationIdCompaniesNewRoute: typeof OrganizationsOrganizationIdCompaniesNewRoute
  OrganizationsOrganizationIdConsolidationNewRoute: typeof OrganizationsOrganizationIdConsolidationNewRoute
  OrganizationsOrganizationIdExchangeRatesNewRoute: typeof OrganizationsOrganizationIdExchangeRatesNewRoute
  OrganizationsOrganizationIdIntercompanyNewRoute: typeof OrganizationsOrganizationIdIntercompanyNewRoute
  OrganizationsOrganizationIdAuditLogIndexRoute: typeof OrganizationsOrganizationIdAuditLogIndexRoute
  OrganizationsOrganizationIdCompaniesIndexRoute: typeof OrganizationsOrganizationIdCompaniesIndexRoute
  OrganizationsOrganizationIdConsolidationIndexRoute: typeof OrganizationsOrganizationIdConsolidationIndexRoute
  OrganizationsOrganizationIdExchangeRatesIndexRoute: typeof OrganizationsOrganizationIdExchangeRatesIndexRoute
  OrganizationsOrganizationIdIntercompanyIndexRoute: typeof OrganizationsOrganizationIdIntercompanyIndexRoute
  OrganizationsOrganizationIdReportsIndexRoute: typeof OrganizationsOrganizationIdReportsIndexRoute
  OrganizationsOrganizationIdConsolidationGroupIdEditRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdEditRoute
  OrganizationsOrganizationIdIntercompanyTransactionIdEditRoute: typeof OrganizationsOrganizationIdIntercompanyTransactionIdEditRoute
  OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute
  OrganizationsOrganizationIdConsolidationGroupIdIndexRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdIndexRoute
  OrganizationsOrganizationIdIntercompanyTransactionIdIndexRoute: typeof OrganizationsOrganizationIdIntercompanyTransactionIdIndexRoute
  OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute
  OrganizationsOrganizationIdCompaniesCompanyIdReportsBalanceSheetRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsBalanceSheetRoute
  OrganizationsOrganizationIdCompaniesCompanyIdReportsCashFlowRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsCashFlowRoute
  OrganizationsOrganizationIdCompaniesCompanyIdReportsEquityStatementRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsEquityStatementRoute
  OrganizationsOrganizationIdCompaniesCompanyIdReportsIncomeStatementRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsIncomeStatementRoute
  OrganizationsOrganizationIdCompaniesCompanyIdReportsTrialBalanceRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsTrialBalanceRoute
  OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute: typeof OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteWithChildren
  OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute
  OrganizationsOrganizationIdCompaniesCompanyIdFiscalPeriodsIndexRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdFiscalPeriodsIndexRoute
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute
  OrganizationsOrganizationIdCompaniesCompanyIdReportsIndexRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdReportsIndexRoute
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdEditRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdEditRoute
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdIndexRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdIndexRoute
}

const OrganizationsOrganizationIdRouteRouteChildren: OrganizationsOrganizationIdRouteRouteChildren =
  {
    OrganizationsOrganizationIdDashboardRoute:
      OrganizationsOrganizationIdDashboardRoute,
    OrganizationsOrganizationIdSettingsRoute:
      OrganizationsOrganizationIdSettingsRouteWithChildren,
    OrganizationsOrganizationIdIndexRoute:
      OrganizationsOrganizationIdIndexRoute,
    OrganizationsOrganizationIdCompaniesNewRoute:
      OrganizationsOrganizationIdCompaniesNewRoute,
    OrganizationsOrganizationIdConsolidationNewRoute:
      OrganizationsOrganizationIdConsolidationNewRoute,
    OrganizationsOrganizationIdExchangeRatesNewRoute:
      OrganizationsOrganizationIdExchangeRatesNewRoute,
    OrganizationsOrganizationIdIntercompanyNewRoute:
      OrganizationsOrganizationIdIntercompanyNewRoute,
    OrganizationsOrganizationIdAuditLogIndexRoute:
      OrganizationsOrganizationIdAuditLogIndexRoute,
    OrganizationsOrganizationIdCompaniesIndexRoute:
      OrganizationsOrganizationIdCompaniesIndexRoute,
    OrganizationsOrganizationIdConsolidationIndexRoute:
      OrganizationsOrganizationIdConsolidationIndexRoute,
    OrganizationsOrganizationIdExchangeRatesIndexRoute:
      OrganizationsOrganizationIdExchangeRatesIndexRoute,
    OrganizationsOrganizationIdIntercompanyIndexRoute:
      OrganizationsOrganizationIdIntercompanyIndexRoute,
    OrganizationsOrganizationIdReportsIndexRoute:
      OrganizationsOrganizationIdReportsIndexRoute,
    OrganizationsOrganizationIdConsolidationGroupIdEditRoute:
      OrganizationsOrganizationIdConsolidationGroupIdEditRoute,
    OrganizationsOrganizationIdIntercompanyTransactionIdEditRoute:
      OrganizationsOrganizationIdIntercompanyTransactionIdEditRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute,
    OrganizationsOrganizationIdConsolidationGroupIdIndexRoute:
      OrganizationsOrganizationIdConsolidationGroupIdIndexRoute,
    OrganizationsOrganizationIdIntercompanyTransactionIdIndexRoute:
      OrganizationsOrganizationIdIntercompanyTransactionIdIndexRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdReportsBalanceSheetRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdReportsBalanceSheetRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdReportsCashFlowRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdReportsCashFlowRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdReportsEquityStatementRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdReportsEquityStatementRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdReportsIncomeStatementRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdReportsIncomeStatementRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdReportsTrialBalanceRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdReportsTrialBalanceRoute,
    OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRoute:
      OrganizationsOrganizationIdConsolidationGroupIdRunsRunIdRouteWithChildren,
    OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdFiscalPeriodsIndexRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdFiscalPeriodsIndexRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdReportsIndexRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdReportsIndexRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdEditRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdEditRoute,
    OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdIndexRoute:
      OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesEntryIdIndexRoute,
  }

const OrganizationsOrganizationIdRouteRouteWithChildren =
  OrganizationsOrganizationIdRouteRoute._addFileChildren(
    OrganizationsOrganizationIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitationsRoute: InvitationsRouteWithChildren,
  LoginRoute: LoginRoute,
  PlatformAdminsRoute: PlatformAdminsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  OrganizationsOrganizationIdRouteRoute:
    OrganizationsOrganizationIdRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
